stolostron/must-gather

collection-scripts/gather

Adds `ns/openshift-operators` namespace to collection on Managed Cluster. This will assist in debugging canary builds.

Add additional ns to collect gatekeeper operator logs

---

Dockerfile.prow
Makefile.prow

- Dockerfile.prow - remove microdnf update. We use the latest image and this fails in prow.
- Makefile.prow - Add dummy unit-test target.

Prow onboarding updates

---

collection-scripts/gather

**Issue:** https://github.com/open-cluster-management/backlog/issues/11138
Adding the open-cluster-management-addon-observability namespace to collection from must-gather. This change is present in 2.3 release, but was missing in 2.2 release. Backport.
**Is this a Hub or Managed cluster change?:** Managed 
**Notes:**
Documenting process for later reference.
How to backport:
1. Clone upstream project `git clone`
2. Checkout Release Branch `git checkout release-2.2`
3. Branch from release Branch `git checkout -B <branch name>`
4. Make your change 
5. Create Pull request into release branch
6. smile :)

Add observability addon namespace to managed collection

---

.github/pull_request_template.md
collection-scripts/gather

When acm is installed in a non default namespace, such as "xyz", our script erroneously checks for the namespace "xyz-hub" instead of "open-cluster-management-hub". This namespace name is fixed, and does not vary with the default namespace. This pull request changes this line of the collection script to use the hardcoded name instead of a variable. 
This pull request also adds a PR template for this repo.
Fix for issue https://github.com/open-cluster-management/backlog/issues/12919 and https://github.com/open-cluster-management/backlog/issues/13016

Collect data when OCM installed in non default namespace

---

collection-scripts/gather

Fix for issue https://github.com/open-cluster-management/backlog/issues/12919 and https://github.com/open-cluster-management/backlog/issues/13016
This problem was also addressed in pr 64 and 66. This pull request backports the fix to release 2.1
When ocm is installed in a non default namespace, such as "xyz", our script erroneously checks for the namespace "xyz-hub" instead of "open-cluster-management-hub". This namespace name is fixed, and does not vary with the default namespace. This pull request changes this line of the collection script to use the hardcoded name instead of a variable.

Collect data when OCM installed in non default namespace (release 2.1)

---

collection-scripts/gather

Fix for issue https://github.com/open-cluster-management/backlog/issues/12919 and https://github.com/open-cluster-management/backlog/issues/13016
This problem was also addressed in pr 64 and 65. This pull request backports the fix to release 2.2
When ocm is installed in a non default namespace, such as "xyz", our script erroneously checks for the namespace "xyz-hub" instead of "open-cluster-management-hub". This namespace name is fixed, and does not vary with the default namespace. This pull request changes this line of the collection script to use the hardcoded name instead of a variable.

Collect data when OCM installed in non default namespace (release 2.2)

---

collection-scripts/gather

Signed-off-by: Gus Parvin <gparvin@redhat.com>
GRC ansible automation CRs should be collected in mustgather.
`policyautomations.policy.open-cluster-management.io`
Hub
**Notes:**

policy automation missing from must gather

---

collection-scripts/gather

**Related Issue:**  open-cluster-management/backlog#14554
Can't seem to create an issue
Added get csv in order to get easy view of what operators are installed in the namespace
Operator information
Hub Cluster
**Notes:**

Added get csv to gather-acm.log at support engineer's request

---

collection-scripts/gather

Signed-off-by: Gus Parvin <gparvin@redhat.com>
**Related Issue:**  https://github.com/open-cluster-management/backlog/issues/14907
Added collection of cluster placement CRs
```
placementdecisions.cluster.open-cluster-management.io
placements.cluster.open-cluster-management.io
```
Hub Cluster 
**Notes:**
Not specific to GRC so not sure why this wasn't already being collected.

add cluster placement to collection

---

collection-scripts/gather

**Related Issue:**  open-cluster-management/backlog#<ISSUE_NUMBER>
https://bugzilla.redhat.com/show_bug.cgi?id=2020356
Support would like to add ocp version information for ease of access
oc version
Hub Cluster and Managed Cluster
**Notes:**

Add oc info to managed and hub logs

---

collection-scripts/gather

**Related Issue:**  https://github.com/stolostron/backlog/issues/18398
PolicySet CRD is introduced in ACM 2.5 and we need to collect CRs for it for troubleshooting
policysets.policy.open-cluster-management.io
Hub Cluster
**Notes:**
Signed-off-by: Yu Cao <ycao@redhat.com>

Collect PolicySet CRs on hub

---

collection-scripts/gather

The `AnsibleJob` resources contain valuable status about automation.
Our product shows this status information so I think it's important
we include this in must gather.  Note that I am not attempting to
gather the job logs from the automation.  For now I'm not sure that is
something we want to collect.
Refs:
- https://github.com/stolostron/backlog/issues/20158
Signed-off-by: Gus Parvin <gparvin@redhat.com>
**Related Issue:**  open-cluster-management/backlog#20158
Provided above
`AnsibleJob`
`Hub`
**Notes:**

We should collect the AnsibleJob resources since ACM creates them

---

collection-scripts/gather

This commit adds some cleanup to the
Ramen resources.
1. Collects all the resources in seperate
directory
2. improves indendation
**Related Issue:**  open-cluster-management/backlog#<ISSUE_NUMBER>
**Notes:**

must-gather: cleanup ramen resources

---

collection-scripts/gather

This commit resolves the syntax issue due to
which the managedcluster details were not collected

managedcluster details are empty

---

collection-scripts/gather

From the hub cluster, we need to dump some information about the assisted-installer resources. To do so, we inspect them in the HUB cluster.
Note: The 'clusterdeployments.hive.openshift.io' is already inspected in previous lines in the script.
**Related Issue:**  [MGMT-9387](https://issues.redhat.com/browse/MGMT-9387)
**What resource is being added**:
```
infraenv.agent-install.openshift.io
clusterImageSet.hive.openshift.io
agentclusterinstall.extensions.hive.openshift.io
baremetalhost.metal3.io
```
Hub Cluster
**Notes:**
In the future, we might want to include some logs from the running pods of the `assisted-service` application.
cc: @mresvanis

MGMT-9387: Inspect assisted-installer CRs in all namespaces

---

collection-scripts/gather

Signed-off-by: Tesshu Flower <tflower@redhat.com>
**Related Issue:** https://github.com/stolostron/backlog/issues/21685
Add VolSync CRs to gather on managed clusters
replicationdestinations.volsync.backube
replicationsources.volsync.backube
Managed Cluster
**Notes:**

Gather info about VolSync CRs on spoke clusters

---

collection-scripts/gather

Add submariner-addon CRs and logs to gather.
Fixes https://github.com/stolostron/backlog/issues/22897
Signed-off-by: Vishal Thapar <5137689+vthapar@users.noreply.github.com>
**Related Issue:**  stolostron/backlog#22897
* Gather submariner-addon CRs
* Gather pod log from submariner-operator namespace
**What resource is being added**: submarinerconfigs.submarineraddon.open-cluster-management.io, brokers.submariner.io
Hub Cluster, Managed Cluster
**Notes:**
Users will still need to run `subctl gather` to capture connectivity data, so this PR is only focussing on addon data which is not covered by subctl currently.

Add submariner data to gather

---

collection-scripts/gather

This commit is a backport of https://github.com/stolostron/must-gather/pull/97 (80401327d39d4c1ca86e08485b470c07b90a7e42)
**Related Issue:**  open-cluster-management/backlog#<ISSUE_NUMBER>
JIRA MGMT-9387
See original PR being backported
See original PR being backported
See original PR being backported
**Notes:**
See original PR being backported

[release-2.4] MGMT-9387: Inspect assisted-installer CRs in all namespaces

---

collection-scripts/gather

This commit collects the output for following
commands:
1. oc get DRCluster
2. oc describe DRCluster
3. oc adm --dest-dir=must-gather inspect DRCluster

Collect output for DRCluster resources

---

collection-scripts/gather

No issue number
Adding objects of cluster version and csv object
Hub cluster
**Notes:**
The version may need to be also ported to the mce must gather image.   This is being done for ease of use of our must gather in anticipation of runs of automated insights rules against the must gather.  There are already parser written for the version, but not how we have it inputted in our log.  I'd like to have this end up in 2.5 and up if possible

add cluster version and csv object outside gather-acm.log

---

collection-scripts/gather

None
Stop collecting `baremetalhost.metal3.io` and `clusterImageSet.hive.openshift.io` under the `# Inspect Assisted-installer CRs` comment because they're already collected in a difference place in the script
Start collecting missing:
* `agent.agent-install.openshift.io`
* `agentclassification.agent-install.openshift.io`
* `agentserviceconfig.agent-install.openshift.io`
* `hypershiftagentserviceconfig.agent-install.openshift.io`
* `nmstateconfig.agent-install.openshift.io`
Also added collection of CRDs to aid automated must-gather reading tools (and it's nice to have in gathers in general)
See description
Hub
**Notes:**
None

Improve collection of Assisted Installer related resources

---

collection-scripts/gather

Signed-off-by: Anxhela <acoba@redhat.com>
**Related Issue:**  [JIRA ISSUE](https://issues.redhat.com/browse/ACM-3267)
**What resource is being added**: search-v2-operator
**Notes:**

ACM-3267 add search-v2-operator to must-gather

---

collection-scripts/mce-gather.sh

clusterpools.hive.openshift.io
clusterclaims.hive.openshift.io
machinepools.hive.openshift.io
managedclustersets.cluster.open-cluster-management.io
managedclustersetbindings.cluster.open-cluster-management.io
managedclusterimageregistries.imageregistry.open-cluster-management.io
Hub Cluster 
**Notes:**
related mce pr: https://github.com/stolostron/backplane-must-gather/pull/21

add clc related resources in 2.7

---

collection-scripts/gather

Related Issue: stolostron/backlog#<ISSUE_NUMBER>
Resolves: https://issues.redhat.com/browse/ACM-4748
Description of Changes:
Add openshift-gitops information
What resource is being added: | N/A
gitopscluster
argocd
applicationsets
managedclustersetbinding
managedclusterset
Is this a Hub or Managed cluster change?:
Hub Cluster
Notes:

add gitops information for acm

---

collection-scripts/gather

**Related Issue:**  stolostron/backlog#: ACM-1301
In ACM 2.8, for the new argoCD pull model feature, we introduced a new CRD: multiclusterapplicationsetreports.apps.open-cluster-management.io. We need to gather these resources from the hub.
**What resource is being added**: multiclusterapplicationsetreports.apps.open-cluster-management.io
Hub Cluster
**Notes:**

Add appsetreport for argo pull model

---

collection-scripts/gather

https://issues.redhat.com/browse/ACM-5426
Add in `do` to fix syntax error
Hub Cluster 
**Notes:**

ACM-5426: fix for loop syntax error

---

collection-scripts/mce-gather.sh

As part of ACM/TALM alignment (CNF-7366) ACM must-gather should include TALM logs and CGUs
Related Issue: https://issues.redhat.com/browse/CNF-7870
Backplane Must-gather PR: https://github.com/stolostron/backplane-must-gather/pull/23
Description of Changes:
adding TALM logs and CGUs
What resource is being added: clustergroupupgrades.ran.openshift.io | N/A
Is this a Hub or Managed cluster change?:
Hub Cluster
Notes:

Include TALM logs and CGUs in must-gather

---

collection-scripts/gather

**Related Issue:**  stolostron/backlog#
Customer creates addondeploymentconfigs. RHACM components also create these objects. They must be collected as part of `must-gather`
**What resource is being added**: addondeploymentconfigs.addon.open-cluster-management.io
Hub Cluster
**Notes:**

collect addondeploymentconfigs via must-gather

---

collection-scripts/mce-gather.sh

Syncing file with 2.7 backplane-must-gather's mce-gather.sh

[2.7] Sync MCE must-gather scripts

---

collection-scripts/mce-gather.sh

**Related Issue:**  
https://issues.redhat.com/browse/ACM-6005
**Description of Changes:** 
Related backplane-must-gather PR is up: https://github.com/stolostron/backplane-must-gather/pull/29
This change will need to be backported to 2.8, 2.7, 2.6, and 2.5 also

ACM-6005 Fix MCE Naming Conventions

---

collection-scripts/mce-gather.sh

**Related Issue:**  N/A
These are used for defining the image ironic should deploy to a host
**What resource is being added**: preprovisioningimages
Hub Cluster
**Notes:**

Add preprovisioning images to must-gather scripts

---

collection-scripts/gather

**Related Issue:** 
None
Targeted ns inspection instead of inspecting all managedcluster namespaces *twice*.  This could reduce the calls from thousands of namespaces to a handful.
None
Hub
**Notes:**
Much smaller scope of change than the re-arch, but this is where the majority of the performance improvement is I believe.

Reduce ns inspect to targeted resources

---

collection-scripts/gather_application_lifecycle_logs

https://issues.redhat.com/browse/ACM-4413
1. append to collect the new cluster-permission API resource in ACM 2.9 release.
2. fix the collection of the multiclusterapplicationsetreports resource, It is namespaced resource
clusterpermission.rbac.open-cluster-management.io
Hub Cluster
**Notes:**

add to collect cluster permission resources

---

Dockerfile
collection-scripts/gather_mce_logs

This change introduces the capability to remove service and event logs for failed MCE agents.
**Related Issue:**  https://issues.redhat.com/browse/MGMT-15578
We are adding an ability to the MCE gather to obtain logs and events from agentclusterinstall CR's that are marked as "failed" where these logs are available.
**Notes:**

MGMT-15578: Gather service and event logs for failed MCE agents

---

Dockerfile

**Related Issue:**  https://issues.redhat.com/browse/ACM-7713
**Description of Changes:** Update image base to use newest `oc` version
**What resource is being added**: N/A
N/A
**Notes:**
A fix was made in `oc` so that ConfigurationPolicies can be correctly gathered by the `oc adm inspect` commands this uses. Without the fix, almost no information about most ConfigurationPolicies will be recorded.

Update origin-cli builder to 4.15

---

collection-scripts/gather_hub_logs
collection-scripts/gather_spoke_logs

https://issues.redhat.com/browse/ACM-9153
the globalhub namespace in incorrect
**Notes:**

update globalhub namespace

---

collection-scripts/gather_hub_logs
collection-scripts/gather_spoke_logs

**Related Issue:**  stolostron/backlog
https://issues.redhat.com/browse/ACM-10405
As globalhub agent running on the ACM hub cluster, so we should add the logic to hub cluster instead of managed cluster.
multicluster-global-hub-agent pod log
Hub Cluster 
**Notes:**

gather globalhub agent pod log

---

Makefile.prow

Partially revert d5acc478aaeb12213774fe68ffbc51645d4fd34b
`Makefile.prow` is used in Prow CI.

Revert `Makefile.prow` removal

---

.tekton/must-gather-acm-210-pull-request.yaml
.tekton/must-gather-acm-210-push.yaml

This update configures the SAST task to upload SARIF results to quay.io for
long-term storage
Related: 
- https://issues.redhat.com/browse/KONFLUX-3663
- https://issues.redhat.com/browse/KONFLUX-2263

fix(KONFLUX-3663): format PipelineRun files and upload SAST results

---

collection-scripts/gather_mce_logs

**Related Issue:** https://issues.redhat.com/browse/ACM-13458
**Description of Changes:** Adds imageclusterinstall to MCE must-gather
**What resource(s) are being added:** `imageclusterinstall.extensions.hive.openshift.io`
**Notes:** Required for image-based-install-operator GA

ACM-13458: Add imageclusterinstall to MCE gather

---

.github/renovate.json

Now that I know I can scriptify editing the target branch, it's trivial to just move the target branch to `main` each time there's an update. (Also, I went ahead an took advantage of the fact that I can update the `Component` object 😄 )

Remove `baseBranches`

---

collection-scripts/gather_hub_logs
collection-scripts/gather_mce_logs

https://issues.redhat.com/browse/ACM-13625
Added `InternalHubComponent` and `InternalEngineComponent` to list of resources for must-gather to extract.
`InternalHubComponent` and `InternalEngineComponent`.
**Notes:**

[ACM-13625] Added internal Installer CRDs to must-gather

---

collection-scripts/gather_hub_logs

story: https://issues.redhat.com/browse/ACM-12718
doc pr: https://github.com/stolostron/rhacm-docs/pull/6971/files#diff-426c3333e3d6698409184255e75546191f82b8b362dc8f713fb9e77a00c289e1R24
Globalhub will install some addons in `open-cluster-management-global-hub-agent-addon` ns, so we need to collect the log in this ns.
resoueces in ns `open-cluster-management-global-hub-agent-addon`
**Notes:**

collect new globalhub ns data

---

collection-scripts/gather_mce_logs

CRD isn't collected when hub isn't self managed
Add CRD collection to must gather when Hub is not self managed
CRD
**Notes:**

Gather CRD when not using self management

---

README.md
build/Dockerfile
build/Dockerfile.rhtap
collection-scripts/gather
collection-scripts/gather_mce_logs
collection-scripts/gather_utils

Previously the `gather_mce_logs` script was sourced so that the hypershift must-gather could pick up the args. This was removed in the refactor, breaking that collection. This restores the logic in a way that aligns with the refactor.
ref: https://issues.redhat.com/browse/ACM-16255

Fix hypershift must-gather

---

collection-scripts/gather_observability_logs
collection-scripts/gather_spoke_logs

https://issues.redhat.com/browse/ACM-22444
Add missing Observability resources to must-gather collection
configmap observability-metrics-custom-allowlist across all namespaces
configmap/cluster-monitoring-config -n openshift-monitoring
configmap/user-workload-monitoring-config -n openshift-user-workload-monitoring
**Notes:**
Could not reopen PR https://github.com/stolostron/must-gather/pull/544 so opening a new one.
@dhaiducek addressed concerns related to use of `--all-namespaces` you pointed out earlier.

collect custom metrics, CMO and user workload configmaps

---

collection-scripts/gather_hub_logs

https://issues.redhat.com/browse/ACM-24644
Add MulticlusterRoleAssignment tomust-gather. 
MulticlusterRoleAssignment resources will create ClusterPermission resources which in turn creates the RBAC resources in the targeted managed clusters. MulticlusterRoleAssignment is namespaced scope **MulticlusterRoleAssignment is only used on hub**
**Notes:**

Add MulticlusterRoleAssignment to must-gather
