- collection-scripts/gather
Adds to HUB collection
- mutatingwebhookconfigurations.admissionregistration.k8s.io
- validatingwebhookconfigurations.admissionregistration.k8s.io 
- syncsets.hive.openshift.io
> collect syncsets for provisioned cluster on hub

- collection-scripts/gather
Updating the must-gather as part of user story https://github.com/open-cluster-management/backlog/issues/10448
> remove the cert-manager gather entries

- DCO
- Dockerfile.prow
- Makefile
- Makefile.prow
- OWNERS
- Add `Dockerfile.prow`
- Add `Makefile.prow`
- Add DCO
- Adding myself `jlpadilla` as an approver in the OWNERS file.
> Prepare repo for prow onboard

- Dockerfile
- Dockerfile.prow
Issue: https://github.com/openshift/release/pull/17092#discussion_r600379798
> Update to latest stable cli image (4.7)

- README.md
Issue: https://github.com/open-cluster-management/backlog/issues/11034
Add space in readme to trigger rebuild of image.
> Remdiate Package Vulnerability

- Dockerfile
- Dockerfile.prow
Issue: https://github.com/open-cluster-management/backlog/issues/11560
- Rebuild the docker image to fix image scan.
> Rebuild to fix docker image scan

- collection-scripts/gather
Signed-off-by: Joshua Packer <jpacker@redhat.com>
* Add ClusterCurator to the inspect command list.
> Add clusterCurators to must-gather

- README.md
**Related Issue:**  open-cluster-management/backlog#13861
**Notes:**
> dummy update to trigger image rebuild

- .travis.yml
**Related Issue:**  open-cluster-management/backlog#10511
Removing release fast-forward
**What resource is being added**: N/A
N/A
**Notes:**
Change related to prow migration
> Remove fast forward

- collection-scripts/gather
Signed-off-by: Yu Cao <ycao@redhat.com>
> remove cispolicies and add configurationpolicies

- collection-scripts/gather
Signed-off-by: Valentina Birsan <vbirsan@redhat.com>
**Related Issue:**  https://github.com/stolostron/backlog/issues/19750
- restores.cluster.open-cluster-management.io
- backupschedules.cluster.open-cluster-management.io
- backupstoragelocations.velero.io
- backups.velero.io
- restores.velero.io
**Is this a Hub or Managed cluster change?:**  HUB
**Notes:**
> collect hub backup and restore resources

- collection-scripts/gather
This commit collects Ramen DR resources.
DRPolicy object
MirrorPeers object
Application namespace resources on the hub:
Channel(s) used by the Subscription(s)
All Subscription(s)
All PlacementRule(s)
DRPlacementControl
> Collect Ramen Resources

- README.md
**Related Issue:**  open-cluster-management/backlog#20401
We just made edits to the prow config, so we are triggering a rebuild upstream to see if our changes solved the package vulnerabilities
None
~~Hub Cluster | Managed Cluster~~ Config Change
**Notes:**
> Trigger Rebuild

- collection-scripts/gather
Signed-off-by: Cameron Wall <cwall@redhat.com>
**Related Issue:**  [open-cluster-management/backlog#19854](https://github.com/stolostron/backlog/issues/19854)
adding another namespace to inspect
Hub Cluster 
**Notes:**
>  add backup

- collection-scripts/gather
This commit collects the output for the
following command:
* oc describe mirrorpeers
* oc get and describe manifestwork
* oc get and describe managedclsuterview
> collect output for ramen resources

- Dockerfile
**Related Issue:**  open-cluster-management/backlog#<ISSUE_NUMBER>
update cli version
https://coreos.slack.com/archives/CUU609ZQC/p1650401873684769?thread_ts=1649801379.544559&cid=CUU609ZQC
**Notes:**
Signed-off-by: Sherin Varughese <shvarugh@redhat.com>
> update cli version

- README.md
Signed-off-by: Sherin Varughese <shvarugh@redhat.com>
**Related Issue:**  open-cluster-management/backlog#22034
**Notes:**
> Image rebuild 2.5

- README.md
Signed-off-by: Erin Murphy <erinmurp@redhat.com>
**Related Issue:**  https://github.com/stolostron/backlog/issues/22225
**Description of Changes:** Update the must-gather images to stolostron URL
**What resource is being added**: N/A
N/A
> change image to point to stolostron repo in README

- collection-scripts/gather
Signed-off-by: Maggie Chen <magchen@redhat.com>
**Related Issue:**  https://github.com/stolostron/backlog/issues/24568
**What resource is being added**: SubscriptionReport, subscriptionstatus, ApplicationSet, Argo application resource
Both
**Notes:**
> Add subscription report

- collection-scripts/gather
* Add subscription report
Signed-off-by: Maggie Chen <magchen@redhat.com>
* Add subscriptionstatus
Signed-off-by: Maggie Chen <magchen@redhat.com>
* Add discovered argo apps and appset
Signed-off-by: Maggie Chen <magchen@redhat.com>
* Remove argo resources as they will cause error
Signed-off-by: Maggie Chen <magchen@redhat.com>
Signed-off-by: Maggie Chen <magchen@redhat.com>
**Related Issue:**  https://github.com/stolostron/backlog/issues/24568
**What resource is being added**: SubscriptionReport, subscriptionstatus, ApplicationSet, Argo application resource
Both
**Notes:**
> Add subscription report (#114)

- README.md
Issue: https://github.com/stolostron/backlog/issues/25685
Created using automation.
> Trigger prow rebuild 2022-09-16

- collection-scripts/gather
This corrects shellcheck error to gather
managedcluster and manifest details
> remove shellcheck error

- collection-scripts/gather
Signed-off-by: Kevin Cormier <kcormier@redhat.com>
**Related Issue:**  stolostron/backlog#25527
**What resource is being added**: consoles.operator.openshift.io
Hub Cluster
**Notes:**
> Gather information about which console plug-ins are enabled

- collection-scripts/gather
Signed-off-by: zhujian <jiazhu@redhat.com>
**Related Issue:**  https://github.com/stolostron/backlog/issues/25468
- Gather information about hosted mode klusterlet
- A cluster may be both hub and spoke, such as local-cluster or hosting cluster
- Fix lints
registration/work agents logs in Hosted mode
**Notes:**
> Gather information about hosted mode klusterlet

- collection-scripts/gather
Signed-off-by: David Luong <dluong@redhat.com>
None
add imagecontentsourcepolicy to must-gather to sense disconnected env
Both
**Notes:**
> add imagecontentsourcepolicy to must-gather to sense disconnected env

- collection-scripts/gather
- collection-scripts/mce-gather.sh
Signed-off-by: Erin Murphy <erinmurp@redhat.com>
> ACM-2463 added mce-must-gather script

- collection-scripts/gather
- collection-scripts/mce-gather.sh
**Related Issue:**  https://issues.redhat.com/browse/ACM-2463
**Description of Changes:** Adds copy of must-gather from backplane-must-gather
**What resource is being added**: MCE
> ACM-2463 : adds mce-must-gather script

- collection-scripts/gather
Signed-off-by: dislbenn <dbennett@redhat.com>
**Related Issue:**  https://issues.redhat.com/browse/ACM-2857
Collecting clusterversion for release-2.6.
- clusterversion
- Hub & Managed Cluster
**Notes:**
> ACM-2857: Update must gather to collect ocp version 2.6

- collection-scripts/gather
Signed-off-by: dislbenn <dbennett@redhat.com>
**Related Issue:**  https://issues.redhat.com/browse/ACM-2857
Collecting clusterversion for release-2.5
**What resource is being added**:
- clusterversion
- Hub & Managed Cluster
**Notes:**
> ACM-2857: Update must gather to collect ocp version 2.5

- collection-scripts/mce-gather.sh
clusterpools.hive.openshift.io
clusterclaims.hive.openshift.io
machinepools.hive.openshift.io 
managedclustersets.cluster.open-cluster-management.io
managedclustersetbindings.cluster.open-cluster-management.io
managedclusterimageregistries.imageregistry.open-cluster-management.io
Hub Cluster
**Notes:**
related pr in mce must-gather: https://github.com/stolostron/backplane-must-gather/pull/18
> add some foundation related resources

- Dockerfile
- OWNERS
**Related Issue:**  N/A
Update the base image used by docker build.
**What resource is being added**:  N/A
N/A
**Notes:**
> Update docker to use openshift/origin-cli:4.12

- collection-scripts/gather
- collection-scripts/mce-gather.sh
**Related Issue:**  https://issues.redhat.com/browse/ACM-2463
**Description of Changes:** Adds copy of must-gather from backplane-must-gather
**What resource is being added**:  MCE
> [release-2.6] ACM-2463 : adds mce-must-gather script

- collection-scripts/gather
- collection-scripts/mce-gather.sh
**Related Issue:**  https://issues.redhat.com/browse/ACM-2463
**Description of Changes:** Adds copy of must-gather from backplane-must-gather
**What resource is being added**: MCE
> [release-2.7] ACM-2463 : adds mce-must-gather script

- collection-scripts/gather
**Related Issue:**  https://issues.redhat.com/browse/ACM-4574
Add Multicluster Global Hub resources for must gather scripts.
**What resource is being added**:
MulticlusterGlobalHub
Kafka
KafkaTopic
PostgresCluster
Also 
added namespaces of kafka-operator and postgres-operator in Hub cluster.
added namespace of `open-cluster-management-global-hub-system` namespace in managed cluster.
Hub Cluster  and Managed Cluster
**Notes:**
> add multicluster global hub resources.

- collection-scripts/mce-gather.sh
issue: https://issues.redhat.com/browse/ACM-4137
> ACM-4137 Sync MCE must-gather

- collection-scripts/mce-gather.sh
Updated the MCE must-gather script.
N/A
N/A
**Notes:**
These change will prevent the `gather-mce.log` from being overwritten in its respected file lines.
> Updated MCE must-gather script

- collection-scripts/mce-gather.sh
**Related Issue:**  https://issues.redhat.com/browse/ACM-6005
**Description of Changes:** Required quick-fix for acm values to not be overwritten by mce
> 2.8 mce sync

- README.md
- collection-scripts/gather_mce_logs
**Related Issue:**  https://issues.redhat.com/browse/ACM-7463
Adding an option to collect must-gather data to troubleshoot a hosted cluster problem.
**What resource is being added**: Documented in the README
Hub Cluster
**Notes:**
> Adding hypershift hosted cluster must gather and documentation

- collection-scripts/gather
https://issues.redhat.com/browse/ACM-9153
the globalhub namespace in incorrect
**Notes:**
> add globalhub inspect

- collection-scripts/gather_hub_logs
- collection-scripts/gather_mce_logs
Signed-off-by: David Luong <dluong@redhat.com>
**What resource is being added**:  Add service account and role information for ACM and MCE
Hub Cluster 
**Notes:**
> Add role and service account information

- collection-scripts/gather_hub_logs
- collection-scripts/gather_spoke_logs
https://issues.redhat.com/browse/ACM-10936
The namespace of globalhub was not correct
**Notes:**
> update the namespace of globalhub

- collection-scripts/gather_hub_logs
None
Added addon proxy config info
managedproxyconfigurations.proxy.open-cluster-management.io               
managedproxyserviceresolvers.proxy.open-cluster-management.io       
Hub Cluster
**Notes:**
> Add proxy config addon info

- .github/pull_request_template.md
- .gitignore
- Dockerfile
- Dockerfile.rhtap
- Makefile
- README.md
**Related Issue:**  https://issues.redhat.com/browse/ACM-10719
**Description of Changes:** Adds Dockerfile for Konflux builds
**What resource is being added**: N/A
**Is this a Hub or Managed cluster change?:** N/A
**Notes:** Also contains minor repo cleanup
> Add Konflux build file

- .gitignore
- Dockerfile
- Dockerfile.rhtap
This matches the `oc` build for 4.15.
ref: https://issues.redhat.com/browse/ACM-10920
> [release-2.11] Upgrade `oc` to 4.16

- collection-scripts/gather_spoke_logs
**Related Issue:** https://issues.redhat.com/browse/ACM-12422
**What resource(s) are being added:** `OperatorPolicy
> Add `OperatorPolicy`

- .tekton/must-gather-acm-212-pull-request.yaml
- .tekton/must-gather-acm-212-push.yaml
- Dockerfile
- Dockerfile.rhtap
- README.md
- build/user_setup
~(Primarily serves as a no-op to kick off the Konflux PR build.)~
Also resolves some Konflux-identified issues:
- Runs image as a non-root user
- Updates the configuration to use `Dockerfile.rhtap`
> Reflow README

- .github/renovate.json
Increase frequency for testing.
> Adjust MintMaker update schedule

- .github/renovate.json
I'm hoping this _might_ resolve the lack of MintMaker updates here.
> [release-2.11] Use array for Renovate schedule

- collection-scripts/gather_hub_logs
Resolves 
**Related Issue:** https://issues.redhat.com/browse/ACM-13623
**Description of Changes:** Adds `ClusterInstance` to ACM must-gather
**What resource(s) are being added:** 
- `clusterinstance.siteconfig.open-cluster-management.io`
**Notes:** Required for SiteConfig operator GA
The SiteConfig operator pods are automatically collected since they deployed under the ACM namespace. The snippet below illustrates the pod logs that are collected for the SiteConfig operator.
```sh
$ ls -lR must-gather/namespaces/rhacm/pods/siteconfig-controller-manager-7f4c885cdc-9cpm2/
total 32
drwxr-xr-x  3 sakhoury  staff     96 31 Aug 10:22 kube-rbac-proxy
drwxr-xr-x  3 sakhoury  staff     96 31 Aug 10:22 manager
-rwxr-xr-x  1 sakhoury  staff  13939 31 Aug …
```
> ACM-13623: Add clusterinstance to ACM gather

- collection-scripts/gather_governance_logs
Gathers PolicyReports
PolicyReports
**Notes:**
> [release-2.11] Gather PolicyReports

- collection-scripts/gather_governance_logs
- collection-scripts/gather_spoke_logs
Adds the resources below.
PolicyReports and the open-cluster-management-policies namespace.
**Notes:**
> Gather some additional policy information

- collection-scripts/gather_spoke_logs
Ref: https://issues.redhat.com/browse/ACM-14832
Gatekeeper operator and Gatekeeper pod logs (verify this)
All ConstraintTemplates and constraints
All CRs related to mutation
_ excludes all pod statuses_
Grep all these:
Gatekeepers.operator.gatekeeper.sh (operator)
assign.mutations.gatekeeper.sh
assignimage.mutations.gatekeeper.sh
assignmetadata.mutations.gatekeeper.sh
configs.config.gatekeeper.sh
constrainttemplates.templates.gatekeeper.sh
expansiontemplate.expansion.gatekeeper.sh
k8srequiredlabels.constraints.gatekeeper.sh (all contraints)
modifyset.mutations.gatekeeper.sh
providers.externaldata.gatekeeper.sh
syncsets.syncset.gatekeeper.sh
**Notes:**
Verify: …
> Improve must gather for Gatekeeper

- collection-scripts/gather_hub_logs
- collection-scripts/gather_mce_logs
N/A
Updated the ACM and MCE must-gather to begin fetching the `ClusterManagementAddOn` resources.
- `ClusterManagementAddOn`
**Notes:**
> Updated must-gather to get clusterManagementAddOn resources

- collection-scripts/gather_mce_logs
**Description of Changes:** Updated the MCE must-gather script to include the latest changes from the `backplane-must-gather`.
1. AddonDeploymentConfigs
2. AddonTemplates
3. CatalogSources
4. Clusters
5. ClusterVersions
6. CustomResourceDefinitions
7. ImageContentSourcePolicies
8. KlusterletConfigs
9. MachinePools
10. PreProvisioningImages
11. RosaControlPlanes
12. RosaMachinePools
**Notes:**
> Synced MCE must-gather script with latest updates

- collection-scripts/gather_hub_logs
Backport of:
[main] https://github.com/stolostron/must-gather/pull/432
[release-2.12] https://github.com/stolostron/must-gather/pull/433
> log DPA and velero Schedules

- README.md
> [release-2.10] No-op

- collection-scripts/gather_application_lifecycle_logs
Add gitops applications
Add gitops applications
applications.argoproj.io
**Notes:**
> Add gitops applications

- .tekton/must-gather-acm-214-push.yaml
Refs:
- https://issues.redhat.com/browse/ACM-20948
**Notes:**
> Add multiarch build to konflux pipeline

- collection-scripts/gather_hub_logs
- collection-scripts/gather_mce_logs
- collection-scripts/gather_utils
https://issues.redhat.com/browse/ACM-14451
Add managed cluster list to `gather-acm.log`
N/A
**Notes:**
> Reformat `gather-acm.log`

- .tekton/must-gather-acm-214-pull-request.yaml
> Update CEL to release-2.14

- .tekton/must-gather-acm-214-pull-request.yaml
> [release-2.14] Update CEL to release-2.14
